## Question 2

#### Part a

In [1]:
# Importing required libraries
from sklearn.linear_model import LinearRegression
import pandas as pd 
import numpy as np 
import warnings 
warnings.filterwarnings("ignore")

In [2]:
# Loading the data
train_df = pd.read_csv('train.data.csv')
test_df = pd.read_csv('test.data.csv')

train_df.head()

Unnamed: 0          id             date    price  bedrooms  bathrooms  \
0           2  6414100192  20141209T000000   538000         3       2.25   
1           4  2487200875  20141209T000000   604000         4       3.00   
2           5  1954400510  20150218T000000   510000         3       2.00   
3           6  7237550310  20140512T000000  1225000         4       4.50   
4           7  1321400060  20140627T000000   257500         3       2.25   

   sqft_living  sqft_lot  floors  waterfront  ...  grade  sqft_above  \
0         2570      7242     2.0           0  ...      7        2170   
1         1960      5000     1.0           0  ...      7        1050   
2         1680      8080     1.0           0  ...      8        1680   
3         5420    101930     1.0           0  ...     11        3890   
4         1715      6819     2.0           0  ...      7        1715   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0            400      1951          1991    98125  47.7210 -122.319   
1            910      1965             0    98136  47.5208 -122.393   
2              0      1987             0    98074  47.6168 -122.045   
3           1530      2001             0    98053  47.6561 -122.005   
4              0      1995             0    98003  47.3097 -122.327   

   sqft_living15  sqft_lot15  
0           1690        7639  
1           1360        5000  
2           1800        7503  
3           4760      101930  
4           2238        6819  

[5 rows x 22 columns]

In [3]:
test_df.head()

Unnamed: 0          id             date   price  bedrooms  bathrooms  \
0           1  7129300520  20141013T000000  221900         3        1.0   
1           3  5631500400  20150225T000000  180000         2        1.0   
2          11  1736800520  20150403T000000  662500         3        2.5   
3          18  6865200140  20140529T000000  485000         4        1.0   
4          20  7983200060  20150424T000000  230000         3        1.0   

   sqft_living  sqft_lot  floors  waterfront  ...  grade  sqft_above  \
0         1180      5650     1.0           0  ...      7        1180   
1          770     10000     1.0           0  ...      6         770   
2         3560      9796     1.0           0  ...      8        1860   
3         1600      4300     1.5           0  ...      7        1600   
4         1250      9774     1.0           0  ...      7        1250   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1              0      1933             0    98028  47.7379 -122.233   
2           1700      1965             0    98007  47.6007 -122.145   
3              0      1916             0    98103  47.6648 -122.343   
4              0      1969             0    98003  47.3343 -122.306   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           2720        8062  
2           2210        8925  
3           1610        4300  
4           1280        8850  

[5 rows x 22 columns]

In [4]:
# Dropping the first column
train_df = train_df.drop(train_df.columns[0], axis=1)
test_df = test_df.drop(test_df.columns[0], axis=1)

In [5]:
# Selecting the predictors and the target
X_train = train_df[["bedrooms","bathrooms","sqft_living","sqft_lot"]]
y_train = train_df["price"]

X_test = test_df[["bedrooms","bathrooms","sqft_living","sqft_lot"]]
y_test = test_df["price"]


In [6]:
# Fitting the model
lm = LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [7]:
# R^2 for training data
lm.score(X_train,y_train)

0.5101138530794578

In [8]:
# R^2 for test data
lm.score(X_test,y_test)

0.5049944614037112

In [9]:
lm.coef_

array([-5.92969566e+04,  3.68165620e+03,  3.16685731e+02, -4.26736772e-01])

In [10]:
lm.intercept_

80832.98911761487

#### Part b

In [11]:
# Loading data for fancy house 
fancy_house = pd.read_csv('fancyhouse.csv')
fancy_house.drop(fancy_house.columns[0], axis=1)

X_fancy = fancy_house[["bedrooms","bathrooms","sqft_living","sqft_lot"]]

In [12]:
fancy_house_cost = lm.predict(X_fancy)[0]
print("The cost of a fancy house is: {:,.2f}".format(fancy_house_cost))

The cost of a fancy house is: 15,436,769.54


House seems to be valued at $130M hence the model doesnt seem to be able to predict the value of the house.

#### Part c

In [13]:
# Feature engineering a new variable
X_train["bed_bath"] = X_train["bedrooms"]*X_train["bathrooms"]
X_test["bed_bath"] = X_test["bedrooms"]*X_test["bathrooms"]

In [14]:
lm.fit(X_train,y_train)

LinearRegression()

In [15]:
lm.score(X_train,y_train)

0.5173532927738305

In [16]:
lm.score(X_test,y_test)

0.5105355458590048

In [17]:
lm.coef_

array([-1.28706409e+05, -1.11008869e+05,  3.08724841e+02, -4.24577540e-01,
        3.37536051e+04])

In [18]:
lm.intercept_

320752.7479766548

Seems to be a slight improvement in the R^2 than before but could be due to high correlation

#### Part d

In [22]:
# Orignal betas 
betas = [lm.intercept_]
betas.append(lm.coef_.tolist())
print("Betas: ",betas)

Betas:  [320752.7479766548, [-128706.4087225894, -111008.8693901701, 308.72484131696547, -0.42457754017959815, 33753.60513846728]]


In [23]:
# Implementing the loss
def loss(X,y,beta):
    """_summary_

    Args:
        X (_type_): _description_
        y (_type_): _description_
        beta (_type_): _description_
    """
    
    return y - X @ beta 
    

# Implementing gradient descent
def gradient_descent(X,y,eta,tau,maxiter = 100000):
    """_summary_

    Args:
        X (_type_): _description_
        y (_type_): _description_
        eta (_type_): _description_
        tau (_type_): _description_
    """
    
    # Generating an initial random beta
    n = X.shape[0]
    p = X.shape[1]
    
    random_betas = np.zeros(shape = (p,1))
    
    for _ in range(maxiter):
        # Calculating the loss 
        l = loss(X,y,random_betas)
        # Calculating the gradient
        gradients = -(2/n) * (X.T @ l)
        
        # Updating the beta
        random_betas = random_betas -eta * gradients
        
        if np.linalg.norm(gradients)<tau:
            break
    

    return random_betas
    

In [17]:
y_train.shape

(15129,)

In [18]:
X_train.shape

(15129, 5)

In [24]:
X_train = np.hstack((np.ones((X_train.shape[0],1)),X_train))

In [25]:
X_train

array([[1.000e+00, 3.000e+00, 2.250e+00, 2.570e+03, 7.242e+03, 6.750e+00],
       [1.000e+00, 4.000e+00, 3.000e+00, 1.960e+03, 5.000e+03, 1.200e+01],
       [1.000e+00, 3.000e+00, 2.000e+00, 1.680e+03, 8.080e+03, 6.000e+00],
       ...,
       [1.000e+00, 2.000e+00, 7.500e-01, 1.020e+03, 1.350e+03, 1.500e+00],
       [1.000e+00, 3.000e+00, 2.500e+00, 1.600e+03, 2.388e+03, 7.500e+00],
       [1.000e+00, 2.000e+00, 7.500e-01, 1.020e+03, 1.076e+03, 1.500e+00]])

In [27]:
y_train = y_train.to_numpy().reshape(-1,1)

In [28]:
y_train.shape

(15129, 1)

In [23]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# X_train_scaled = scaler.fit_transform(X_train)

In [29]:
betas = gradient_descent(X_train,y_train,10e-15,10e-6)

In [30]:
betas

array([[9.58092202e-04],
       [3.42405295e-03],
       [2.29393494e-03],
       [2.40491976e+00],
       [5.16196685e+00],
       [8.65027420e-03]])

In [33]:
X_test = np.hstack((np.ones((X_test.shape[0],1)),X_test))

In [34]:
predictions = X_test @ betas

In [36]:
y_test = y_test.to_numpy().reshape(-1,1)

In [40]:
predictions

array([[32002.9574936 ],
       [53471.48411133],
       [59128.22345289],
       ...,
       [ 9395.77283826],
       [37151.03102703],
       [45607.57346862]])

In [42]:
y_test

array([[ 221900],
       [ 180000],
       [ 662500],
       ...,
       [ 429000],
       [ 610685],
       [1007500]], dtype=int64)

In [46]:
from sklearn.metrics import r2_score

In [47]:
corr_matrix = np.correlate(y_test.flatten(),predictions.flatten(),mode='full')

R_sq = r2_score(y_test,predictions)
print(R_sq)

-1.877300655229594


In [38]:
corr_matrix

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

e. Stochastic Gradient

In [26]:
from sklearn.linear_model import SGDRegressor

In [39]:
lm_sgd = SGDRegressor()

In [40]:
lm_sgd.fit(X_train,y_train)

SGDRegressor()

In [41]:
lm_sgd.coef_

array([ 1.01240803e+11,  3.89446714e+11,  4.15582302e+11, -4.01680109e+12,
       -4.93370086e+13,  1.03478261e+12])